### ISSUE TITLE
关机正常吗？

### ISSUE THREAD

**Issue by kongminhao** [Asphyxia-m/Asus-ROG-STRIX-Z390-F-Gaming-EFI#1]
hello，我用了你的EFI，配置为 9700KF + z390-F + 5700xt。我发现关机时会先正常关机，然后自动（瞬间）断电, 然后再开机的话就会卡F1了，机型已更改为iMacPro1,1。

**Comment by kongminhao** [comment]
有什么思路或者方向吗？

**Comment by Asphyxia-m** [comment]
@kongminhao 您好,我的配置为双显卡,如果9700kf是没有核显的所以要更改机型为iMac Pro1,1,并且在config.plist -> config->DeviceProperties->删除AAPL,ig-platform-id选项 望知悉

**Comment by kongminhao** [comment]
Thanks♪(･ω･)ﾉ。我试试。
