### ISSUE TITLE
安装黑屏原因求指导

### ISSUE THREAD

**Issue by bing0ye** [Asphyxia-m/Asus-ROG-STRIX-Z390-F-Gaming-EFI#2]
Hi，你好，我的配置和你的类似，但是在安装的过程出现了错误

配置如下
CPU：9700k
主板：Strix Z390-F Gaming
内存：芝奇幻光戟3200 8*2
硬盘：三星970EVO
网卡：BCM94360CD
HDMI接口，无独显

我对你的EFI进行了修改，把独显部分的配置改为了核显。为了查看日志，在boot-args加了-v。在安装10.15.4时黑屏了，报错gIOScreenLockState 3, hs 0, bs 0, now 0，但是在网上搜所后还是没解决，希望得到你的帮助，谢谢

**Comment by Asphyxia-m** [comment]
config->PciRoot(0x0)/Pci(0x2,0x0)->选项添加内容如下

1. AAPL,ig-platform-id     data    <07009b3e>
2. device-id               data    <9b3e0000>
3. enable-hdmi20           data    <01000000>
4. framebuffer-unifiedmem  data    <00000080>

boot-args 参数为 Slide=1 darkwake=0 -v

**Comment by bing0ye** [comment]
这些参数都设置了，今天我换DP线，没问题了，8代核显HDMI调起来很麻烦

**Comment by ducanh2110** [comment]
@Asphyxia-m hi, I have a same pc except RX5700. Can I use your configuration you paste above to use. I have the same problem with the topic's author. I got black screen when I'm trying to install. I already do your config with catalina 10.15.5 and it stuck. I am downing to 10.15.3 to test your configuration.

**Comment by ducanh2110** [comment]
![E9BF3AEA-D3E5-4DB7-B349-35426C0F24F2](https://user-images.githubusercontent.com/13704782/83409423-93a1bf00-a43e-11ea-8043-bab82cfffc3d.jpeg)
I got stuck here help me bro @Asphyxia-m
